use linguist_types::{Heuristics, Languages, VendorPatterns};
use std::sync::LazyLock;

// Load up static references to the linguist data generated by build.rs
// These are wrapped in LazyLock to avoid doing any unnecessary work
//

const LANGUAGES_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/languages.json"));
const HEURISTICS_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/heuristics.json"));
const VENDOR_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/vendor.json"));

pub static LANGUAGES: LazyLock<Languages> = LazyLock::new(|| {
    serde_json::from_slice(LANGUAGES_DATA)
        .expect("Failed to deserialize languages.json - this is a bug in the build process")
});

pub static HEURISTICS: LazyLock<Heuristics> = LazyLock::new(|| {
    serde_json::from_slice(HEURISTICS_DATA)
        .expect("Failed to deserialize heuristics.json - this is a bug in the build process")
});

pub static VENDOR: LazyLock<VendorPatterns> = LazyLock::new(|| {
    serde_json::from_slice(VENDOR_DATA)
        .expect("Failed to deserialize vendor.json - this is a bug in the build process")
});
